### PR TITLE
Auto Suggest component made and used in petition update page

### PR DESCRIPTION
**Pull request by Wanna-be-Coder**
I created a auto suggest component such that the users can select a field from the arrays in data file and also type in their own values I tried to keep the structure similar to the other components that were made. The AutoSuggest is similar to the normal input component but has some extra fields namely: 
 suggestions?: string[];
    handleChange: (
        name: 'target' | 'location' | 'title' | 'description',
        value: string,
    ) => void;
    name: 'target' | 'location' | 'title' | 'description';
  I used it in the create/edit petition page

### CODE REVIEW

**Comment by omranjamal** [comment]
Hey, I feel like this is causing a lot of UI reflow, would it be possible to make the suggestions floating instead of adding it to main flow of the UI?

**Comment by Wanna-be-Coder** [comment]
Deleted the component and brought the code to the page also added a new array named cities in data for area suggestions

**Comment by omranjamal** [comment]
This is still causing the entire page to reflow again, hence can't merge this.

**Comment by omranjamal** [comment]
Please feel fre to send us another PR when you improve the experience a bit.

**Pull request closed without merging**
