### PR TITLE
Rich Text Editor

### PR DESCRIPTION
**Pull request by ZahinPrangon**
Screenshot 2024-09-04 at 7 50 26 AM

Issue Tracking:
https://github.com/jonogon/jonogon-mono/issues/39

### CODE REVIEW

**Comment by riya09** [comment]
Hi @ZahinPrangon do you wish to continue working on this?

**Comment by Tohid001** [comment]
> Hi @ZahinPrangon do you wish to continue working on this?

Hey @riya09, let me know if you are willing to work on this PR. I am also eager to continue this PR.

**Comment by riya09** [comment]
> > Hi @ZahinPrangon do you wish to continue working on this?
> 
> Hey @riya09, let me know if you are willing to work on this PR. I am also eager to continue this PR.

Hi
If you are willing to work on this, I would suggest do a new PR and fetch the latest changes. There has been lot going in the last 2 months and lot of structure in the project has changed.

I am closing this PR for now.

**Comment by riya09** [comment]
@ZahinPrangon fetch the latest changes and make a new PR please.

**Comment by Tohid001** [comment]
> @ZahinPrangon fetch the latest changes and make a new PR please.
yeah sure. on it

**Pull request closed without merging**
